from __future__ import annotations

import uuid
from typing import Protocol

from arc.domain.organization.entity import Organization, OrganizationMember


class OrganizationRepositoryProtocol(Protocol):
    async def create(self, org: Organization) -> Organization: ...
    async def get_by_id(self, org_id: uuid.UUID) -> Organization | None: ...
    async def get_by_slug(self, slug: str) -> Organization | None: ...
    async def update(self, org: Organization) -> None: ...


class OrganizationMemberRepositoryProtocol(Protocol):
    async def add(self, member: OrganizationMember) -> OrganizationMember: ...
    async def remove(self, org_id: uuid.UUID, user_id: uuid.UUID) -> bool: ...
    async def get_member(
        self, org_id: uuid.UUID, user_id: uuid.UUID,
    ) -> OrganizationMember | None: ...
    async def list_by_org(self, org_id: uuid.UUID) -> list[OrganizationMember]: ...
    async def list_orgs_for_user(self, user_id: uuid.UUID) -> list[OrganizationMember]: ...
    async def count_members(self, org_id: uuid.UUID) -> int: ...
